### PR TITLE
CW-16: Added events to homepage

### PR DESCRIPTION
**Pull request by lewisnyman**
It could do with another event to fill it up. Maybe Teacamp?

screenshot 2018-08-17 15 56 03

### CODE REVIEW

**Comment by steveparks** [comment]
New event:
Steve Parks will be at Silent GovCamp (http://govcampcymru.org/silentcamp)
18th October

**Comment by lewisnyman** [comment]
Steve Parks [11:46 AM]
Other events coming up, for which i reserved tickets ages back, but we now need to work out if we can use them….

1. Local Govcamp is in Birmingham on Sat 22nd Sept. Unfortunately I can’t go as it’s my dad’s 80th birthday, and Joe can’t go because Sarah’s away - but he offers a bed and beer to anyone that fancies visiting brum that day
2. UK Healthcamp is in Manchester on Sat 8th Sept. If needed I could probably rearrange things to go, but it’ll be a bit of a pain, so if anyone is up for going that’d be great
and also, there are waiting lists, so if we don’t want to go to any of these, we can release our tickets back. but they can be useful places to show our faces and meet people

**Comment by lewisnyman** [comment]
@steveparks Is this good for merging now?

**Comment by steveparks** [comment]
Yes!

**Pull request merged**
