### PR TITLE
Added netlify forms support

### PR DESCRIPTION
**Pull request by lewisnyman**

### CODE REVIEW

**Comment by steveparks** [comment]
What functionality / improvement does netlify provide?

**Comment by lewisnyman** [comment]
@steveparks It's about the same, but it means I can stop paying for simpleforms on my paypal account. Netlify is a lot more mature and less bootstrappy than simpleforms too, it feels more reliable.

**Comment by lewisnyman** [comment]
Talking to Netlify support about why this doesn't work in the deploy preview

**Comment by lewisnyman** [comment]
Netlify fixed this for us. Thanks!

**Pull request merged**
