### PR TITLE
Added the logo to the site but ended up making a few more design...

### PR DESCRIPTION
**Pull request by lewisnyman**
…changes so it didn't feel out of place

### CODE REVIEW

**Comment by lewisnyman** [comment]
Screenshots

screenshot 2016-10-07 10 10 59
screenshot 2016-10-07 10 10 53
screenshot 2016-10-07 10 10 42
screenshot 2016-10-07 10 10 28
screenshot 2016-10-07 10 10 21
screenshot 2016-10-07 10 09 55

**Comment by mikebell** [comment]
How come Steve Huntons name isn't bold? Is that a visited state?

Other than that it looks great.

**Comment by lewisnyman** [comment]
Oh yeah, there's a visited state color trickling in somehow. Weird.

**Comment by lewisnyman** [comment]
More screenshots

screenshot 2016-10-07 12 31 26
screenshot 2016-10-07 12 31 21
screenshot 2016-10-07 12 31 15
screenshot 2016-10-07 12 31 05
screenshot 2016-10-07 12 30 59
screenshot 2016-10-07 12 30 48

**Comment by lewisnyman** [comment]
Merging this for now so I can get on with V2 instead of this halfway house

**Pull request merged**
